env:
  CIRRUS_CLONE_DEPTH: "1"
  GITHUB_TOKEN: "ENCRYPTED[!37f49a3c2ff53ae3cd6478518356b31d939652e0113563bc5eb7810872807212776b2a02c17c21f6228eb967162fb357!]"

arm64_task:
  name: ARM64 build
  timeout_in: 120m
  container:
    image: fedora:latest
    cpu: 8
    memory: 12G
  setup_env_script:
    - dnf -y upgrade
    - dnf -y groupinstall development-tools
    - dnf -y install binutils-devel bison bzip2 ccache clang cmake flex g++ glibc-devel glibc-devel.i686 gmp-devel libmpc-devel lld llvm llvm-devel mpfr-devel ninja-build rclone tar texinfo which zlib-devel
    - chmod a+x ci.sh
  build_script:
    - bash ci.sh --arm64

arm_task:
  name: ARM build
  timeout_in: 120m
  container:
    image: fedora:latest
    cpu: 8
    memory: 12G
  setup_env_script:
    - dnf -y upgrade
    - dnf -y groupinstall development-tools
    - dnf -y install binutils-devel bison bzip2 ccache clang cmake flex g++ glibc-devel glibc-devel.i686 gmp-devel libmpc-devel lld llvm llvm-devel mpfr-devel ninja-build rclone tar texinfo which zlib-devel
    - chmod a+x ci.sh
  build_script:
    - bash ci.sh --arm
