name: ARM64 GCC+LLD Build

on:
  push:
  schedule:
    - cron: '0 0 * * 0,4'

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: fedora:rawhide

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo dnf groupinstall "Development tools" -y
        sudo dnf install mpfr-devel gmp-devel libmpc-devel zlib-devel glibc-devel.i686 glibc-devel binutils-devel g++ texinfo bison flex cmake which ninja-build clang lld -y
    - name: Set build date
      id: get-date
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    - name: Build & Push
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/mvaisakh/arm64-gcc ../gcc-arm64 -b gcc-master
        rm -rf ../gcc-arm64/*
        chmod a+x build-*.sh
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<b>Starting ARM64 GCC Build</b>"
        ./build-gcc.sh -a arm64
        ./build-lld.sh -a arm64
        script_dir=$(pwd)
        cd ../gcc-arm64
        ./bin/aarch64-elf-gcc -v 2>&1 | tee /tmp/gcc-version
        ./bin/aarch64-elf-ld.lld -v 2>&1 | tee /tmp/lld-arm64-version
        bash "$script_dir/strip-binaries.sh"
        git add . -f
        git commit -as -m "Import ARM64 GCC $(/bin/date -u "+%Y%m%d")" -m "Build completed on: $(/bin/date)" -m "Configuration: $(/bin/cat /tmp/gcc-version)" -m "LLD: $(/bin/cat /tmp/lld-arm64-version)"
        git gc
        git push origin gcc-master -f
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_USER: ${{ secrets.USERNAME }}
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT }}
    - uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.CHAT }} # user id or channel name secret
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }} # token secret
        status: ${{ job.status }} # do not modify this line
